language: java

cache:
  directories:
  - $HOME/.m2
  
addons:
  sonarcloud:
    organization: "grillbaer"

script:
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
